#!/bin/bash

# ibrunton's herbstluftwm config
# 2012-05-06

function hc () {
	herbstclient "$@"
}

hc emit_hook reload

hc keyunbind --all
hc mouseunbind

# make room for conky
hc pad 0 10 0 0

# variables
colour_normal='#ae8451'
colour_active='#f6ff00'
terminal=urxvt
emacs=emet
file_manager=dolphin
browser=firefox

# keybindings
mod=Mod4

# programs & overall functions
hc keybind $mod-Control-Shift-r reload
hc keybind $mod-Shift-q quit
hc keybind $mod-Shift-c close
hc keybind $mod-Return spawn $terminal
hc keybind $mod-Shift-Return spawn $emacs
hc keybind $mod-Shift-Escape spawn $HOME/bin/slrh.sh
hc keybind $mod-p spawn dmenu_run -fn "-misc-ohsnap-medium-r-normal--11-79-100-100-c-60-iso8859-1" -nb '#000000' -nf '#e0e0e0' -sb '#000000' -sf '#4abcd4'
#hc keybind $mod-p spawn dmenu_run -i -nb '#000000' -nf '#e0e0e0' -sb '#000000' -sf '#4abcd4'
hc keybind $mod-Shift-p spawn $HOME/bin/dmenu_custom.bash
hc keybind $mod-w spawn $browser
hc keybind $mod-t spawn $file_manager
#hc keybind $mod-b # hide conky
#hc keybind $mod-m # dzen menu?

# keybindings: tags
TAG_NAMES=( {1..6} )
TAG_KEYS=( {1..6} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
	hc add "${TAG_NAMES[$i]}"
	key="${TAG_KEYS[$i]}"
	if ! [-z "$key" ] ; then
		hc keybind "$mod-$key" use "${TAG_NAMES[$i]}"
		hc keybind "$mod-Shift-$key" move "${TAG_NAMES[$i]}"
	fi
done

# keybindings: layout
hc keybind $mod-Control-d remove
hc keybind $mod-Space floating toggle
hc keybind $mod-a split horizontal 0.5
hc keybind $mod-s split horizontal 0.33
hc keybind $mod-z split vertical 0.5
hc keybind $mod-x split vertical 0.33

# keybindings: resizing
RESIZESTEP=0.05
hc keybind $mod-Control-h resize left +$RESIZESTEP
hc keybind $mod-Control-k resize down +$RESIZESTEP
hc keybind $mod-Control-j resize up +$RESIZESTEP
hc keybind $mod-Control-l resize right +$RESIZESTEP

# keybindings: focus
hc keybind $mod-Tab cycle_all +1
hc keybind $mod-Shift-Tab cycle_all -1
hc keybind $mod-c cycle
hc keybind $mod-h focus left
hc keybind $mod-j focus down
hc keybind $mod-k focus up
hc keybind $mod-l focus right
hc keybind $mod-Shift-h shift left
hc keybind $mod-Shift-j shift down
hc keybind $mod-Shift-k shift up
hc keybind $mod-Shift-l shift right

# keybindings: volume
hc keybind $mod-F10 spawn amixer -q sset Master 1- unmute
hc keybind $mod-F11 spawn amixer -q sset Master toggle
hc keybind $mod-F12 spawn amixer -q sset Master 1+ unmute

# colours/appearance
hc set default_frame_layout 1
hc set frame_bg_transparent 1
hc set frame_border_width 0
hc set window_border_width 1
hc set window_border_normal_color $colour_normal
hc set window_border_active_color $colour_active
hc set window_gap 5
hc set snap_distance 20

# floating tags
hc floating 3 on
hc floating 5 on
hc floating 6 on
hc set raise_on_click 1
hc set raise_on_focus 1

# mouse buttons
hc mousebind $mod+Button1 move
hc mousebind $mod+Button3 resize

# rules
hc unrule -F
hc rule focus=on
hc rule class=Firefox tag=2
hc rule class=gimp tag=6 pseudotile=on
hc rule class=Okular tag=5
hc rule class=URxvt instance=MAILTO pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_DIALOG' pseudotile=on
hc rule class=Kdialog pseudotile=on
